name: Release

on:
  pull_request_target:
    types: [closed]

jobs:
  release_job:
    uses: bedita/github-workflows/.github/workflows/release.yml@v1
    with:
      main_branch: '5-salix'
      dist_branches: '["5-salix","4-cactus"]'
      version_ini_path: plugins/BEdita/Core/config/bedita.ini
      version_ini_prefix: "[BEdita]\nversion = "

  filter_tree:
    needs: release_job
    uses: ./.github/workflows/filter-components.yml
    secrets: inherit

  docker_push:
    runs-on: 'ubuntu-latest'
    needs: release_job
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug output version
        run: |
          echo version var ${{ needs.release_job.outputs.version }}

      - name: Update version file
        run: |
          echo "[BEdita]\nversion = ${{ needs.release_job.outputs.version }}" > plugins/BEdita/Core/config/bedita.ini

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: '${{ github.repository }}'
          registry: docker.io
          tags: ${{ needs.release_job.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
